{% set name = "czml3" %}
{% set version = "4.0.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b24866c5f30c9217445759c2cd080e99970324b97d1ab0dec4f8845e9907ebd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77
  run:
    - python >={{ python_min }}
    - pydantic >=2.10.1
    - python-dateutil >=2.7,<3
    - StrEnum >=0.4.0
    - typing-extensions >=4.12.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - czml3
    - czml3.enums
    - czml3.properties
    - czml3.types
  commands:
    - pip check

about:
  home: https://github.com/Stoops-ML/czml3/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: czml3 is a Python library to write CZML

  dev_url: https://github.com/Stoops-ML/czml3/

extra:
  recipe-maintainers:
    - Stoops-ML
