{% set name = "czml3" %}
{% set version = "2.3.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5581fcae835db1818eed9cbbbf9bb1662d63b9b8a2618659f0c510eb80d701b0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pydantic >=2.10.1
    - python-dateutil >=2.7,<3
    - w3lib
    - StrEnum >=0.4.0
    - typing-extensions >=4.12.0
    - numpy

test:
  imports:
    - czml3
    - czml3.enums
    - czml3.properties
    - czml3.types
    - czml3.widget

about:
  home: https://github.com/Stoops-ML/czml3/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: czml3 is a Python library to write CZML

  dev_url: https://github.com/Stoops-ML/czml3/

extra:
  recipe-maintainers:
    - Stoops-ML
