{% set name = "czml3" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70a5413dce5f3d7aea532af57acffadadee0ceb5b915ec617879fab8a61a0dfa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - pydantic >=2.10.1
    - python-dateutil >=2.7,<3
    - w3lib
    - StrEnum >=0.4.0
    - typing-extensions >=4.12.0

test:
  imports:
    - czml3
    - czml3.enums
    - czml3.properties
    - czml3.types
    - czml3.widget

about:
  home: https://github.com/poliastro/czml3/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: czml3 is a Python library to write CZML

  dev_url: https://github.com/poliastro/czml3/

extra:
  recipe-maintainers:
    - astrojuanlu
